parameters:
    qaraqter_questionnaire.twig.extension.questionnaire.class: Qaraqter\QuestionnaireBundle\Twig\QuestionnaireExtension

services:
    qaraqter_questionnaire.form_type.multiple_choice:
        class: Qaraqter\QuestionnaireBundle\Form\Type\MultipleChoiceType
        tags: [{ name: form.type, alias: multiple_choice }]

    qaraqter_questionnaire.form_type.group:
        class: Qaraqter\QuestionnaireBundle\Form\Type\GroupType
        tags: [{ name: form.type, alias: group }]
       
    qaraqter_questionnaire.form_type.header:
        class: Qaraqter\QuestionnaireBundle\Form\Type\HeaderType
        tags: [{ name: form.type, alias: header }]

    qaraqter_questionnaire.form_type.body:
        class: Qaraqter\QuestionnaireBundle\Form\Type\BodyType
        tags: [{ name: form.type, alias: body }]

    qaraqter_questionnaire.form_type.footer:
        class: Qaraqter\QuestionnaireBundle\Form\Type\FooterType
        tags: [{ name: form.type, alias: footer }]

    qaraqter_questionnaire.form_type.previous:
        class: Qaraqter\QuestionnaireBundle\Form\Type\PreviousType
        tags: [{ name: form.type, alias: previous }]

    qaraqter_questionnaire.form_type.next:
        class: Qaraqter\QuestionnaireBundle\Form\Type\NextType
        tags: [{ name: form.type, alias: next }]
    
    qaraqter_questionnaire.form_type.pagination:
        class: Qaraqter\QuestionnaireBundle\Form\Type\PaginationType
        arguments: [@doctrine.orm.default_entity_manager]
        tags: [{ name: form.type, alias: pagination }]
    
    qaraqter_questionnaire.form_extension.form_type:
        class: Qaraqter\QuestionnaireBundle\Form\Extension\FormTypeExtension
        tags: [{ name: form.type_extension, alias: form }]
    
    qaraqter_questionnaire.twig.extension.questionnaire:
        class: %qaraqter_questionnaire.twig.extension.questionnaire.class%
        tags: [{ name: twig.extension }]
